spring:
  datasource:
    url: jdbc:postgresql://${DBPROJECT_HOST}:${DBPROJECT_PORT}/${DBPROJECT_DBNAME}
    username: ${DBPROJECT_NAME}
    password: ${DBPOJECT_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled:false
